[package]
name = "tiv-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tiv-core = { path = "../tiv-core" }
tiv-runtime = { path = "../tiv-runtime" }

[[bin]]
name = "tiv"
path = "src/main.rs"

[lints]
workspace = true
